### ISSUE TITLE
Add registration/login feature

### ISSUE THREAD

**Issue by akshatnema** [akshatnema/Vehicle-Servicing-Management#14]
## Description
This Project has a good UI given for both customer login/registration and admin login. But it doesn't have a backend facility that integrates with the database to create valid user login/registration.

## Solution
Add a proper backend facility on the server-side to enable proper registration and login of customers, and also have admin login.

**Comment by dyarawilliams** [comment]
Hi @akshatnema can I attempt this?

**Comment by dyarawilliams** [comment]
Okay thank you @akshatnema .
