### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by dyarawilliams** [akshatnema/Vehicle-Servicing-Management#22]
Noticed that on the User Registration Form there is a spelling error.

**Comment by akshatnema** [comment]
Hey @dyarawilliams, I just searched this on Google and got these results. Spelling is fine with 'Registration' in British accent. There may be issues with the different accents of English used around the world. So, I can't accept the PR related to this issue. Thanks for your contribution. There are many issues still on this project, where you can work on.

![image](https://user-images.githubusercontent.com/76521428/137574872-c1493bb8-d949-435e-a473-f05401a639b1.png)
